pipeline{
  agent any
  stages{
    stage("version"){
      steps{
        sh "python3 --version"
      }
    }
    stage("demo"){
      steps{
        sh "python3 ./Python/demo.py"
      }
    }
  }
}
